### ISSUE TITLE
panic in the production server

### ISSUE THREAD

**Issue by shengery** [gobwas/ws#54]
Greetings,

We are deploying our chat servers in the production env, the connsrv is the gateway server between clients and internal logic server, which is serving websocket requests , however , we met an unusual panic last day
The panic  stack is : 
```
panic: runtime error: makeslice: len out of range

goroutine 5626477 [running]:
aladinfun.com/midware/goim/vendor/github.com/gobwas/ws.ReadFrame(0x7f5be12140c0, 0xc42000ece0, 0x60700, 0x2424ebb535b8385d, 0xfba2344b01, 0x0, 0x0, 0x0, 0x0, 0x0)
 /data/home/user_00/go_workspace/src/aladinfun.com/midware/goim/vendor/github.com/gobwas/ws/read.go:115 +0xd7
aladinfun.com/midware/goim/srv/connsrv.wsReceive(0xe4a5e0, 0xc42000ece0, 0x8, 0x9d4440, 0xc422d8c730, 0xc4231811e0, 0x18)
 /data/home/user_00/go_workspace/src/aladinfun.com/midware/goim/srv/connsrv/conn_ws.go:49 +0xa6
aladinfun.com/midware/goim/srv/connsrv.clientLoop(0xe4a5e0, 0xc42000ece0, 0xc4203e2f80)
 /data/home/user_00/go_workspace/src/aladinfun.com/midware/goim/srv/connsrv/conn_handler.go:49 +0x150
aladinfun.com/midware/goim/srv/connsrv.uriRoute(0xe4a5e0, 0xc42000ece0, 0xc4203e2f80)
 /data/home/user_00/go_workspace/src/aladinfun.com/midware/goim/srv/connsrv/conn_listener.go:85 +0x133
aladinfun.com/midware/goim/srv/connsrv.handleConn(0xe4a5e0, 0xc42000ece0)
 /data/home/user_00/go_workspace/src/aladinfun.com/midware/goim/srv/connsrv/conn_listener.go:69 +0x25f
created by aladinfun.com/midware/goim/srv/connsrv.listenTCP
 /data/home/user_00/go_workspace/src/aladinfun.com/midware/goim/srv/connsrv/conn_listener.go:57 +0x4fd
```
The location of the panic in read.go is : 
```go
func ReadFrame(r io.Reader) (f Frame, err error) {
	f.Header, err = ReadHeader(r)
	if err != nil {
		return
	}

	if f.Header.Length > 0 {
		// int(f.Header.Length) is safe here cause we have
		// checked it for overflow above in ReadHeader.
                //  panic here!! 
		f.Payload = make([]byte, int(f.Header.Length))
		_, err = io.ReadFull(r, f.Payload)
	}

	return
}
```
However , we don't know how much the frame.length is..

The ```/data/home/user_00/go_workspace/src/aladinfun.com/midware/goim/srv/connsrv/conn_ws.go:49``` is below 
```go
45 func wsReceive(conn net.Conn) (data []byte, err error) {
46	if config.SrvCfg.ClientTimeoutR != 0 {
47 		conn.SetReadDeadline(time.Now().Add(time.Duration(config.SrvCfg.ClientTimeoutR) * time.Millisecond))
48 	}
49 	frm, err := ws.ReadFrame(conn)
50 	if err != nil {
51 		xlog.LevelLogfn(logger.DebugLog, "ws ReadFrame failed, %s", err.Error())
52 		return
53 	}
54 	if frm.Header.Masked {
55		ws.Cipher(frm.Payload, frm.Header.Mask, 0)
56	}
57
58	data = frm.Payload
59	// if data, _, err = crypto.Base64Decode(frm.Payload); err != nil {
60	// 	xlog.LevelLogfn(logger.DebugLog, "base64 decode failed, %s", err.Error())
61	// 	return
62	// }
63	xlog.LevelLogfn(logger.TraceLog, "receive buffer: %v", data)
64	return
65 }
```

**Comment by shengery** [comment]
Do you mean that I handle the frame.Header in my code instead of directly calling ws.ReadFrame?

**Comment by gobwas** [comment]
Yes, `ReadFrame()` just makes `ReadHeader()` and then `make([]byte, header.Length)`.

**Comment by shengery** [comment]
OK,thanks for your reply, I will call ReadHeader and readbody seperately
