### ISSUE TITLE
[signal SIGSEGV: segmentation violation code=0x2

### ISSUE THREAD

**Issue by changlin19** [gobwas/ws#63]
```
unexpected fault address 0x4128c0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x2 addr=0x4128c0 pc=0x4128c0]

goroutine 3029725 [running]:
runtime.throw(0x8c0392, 0x5)
	/usr/lib/golang/src/runtime/panic.go:605 +0x95 fp=0xc48b1dae38 sp=0xc48b1dae18 pc=0x42d1c5
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:374 +0x227 fp=0xc48b1dae88 sp=0xc48b1dae38 pc=0x443d07
runtime.newobject(0x8755a0, 0x20)
	/usr/lib/golang/src/runtime/malloc.go:839 fp=0xc48b1dae90 sp=0xc48b1dae88 pc=0x4128c0
vendor/github.com/gobwas/ws/wsutil.NewCipherReader(...)
	/data/jenkins/workspace/src/xxxxxx/vendor/github.com/gobwas/ws/wsutil/cipher.go:21
vendor/github.com/gobwas/ws/wsutil.(*Reader).NextFrame(0xc45c5ad400, 0x1a23a98301020001, 0x20, 0x7f8d484ec060, 0xc46798c5b8)
	/data/jenkins/workspace/src/xxxxxx/vendor/github.com/gobwas/ws/wsutil/reader.go:175 +0x36c fp=0xc48b1daf20 sp=0xc48b1dae90 pc=0x725bec
vendor/github.com/gobwas/ws/wsutil.readData(0x7f8d484ab220, 0xc46798c5b8, 0x301, 0xb3, 0xc0, 0x0, 0x0, 0xc45ffdfc20, 0x24)
	/data/jenkins/workspace/src/xxxxxx/vendor/github.com/gobwas/ws/wsutil/helper.go:258 +0x16a fp=0xc48b1db010 sp=0xc48b1daf20 pc=0x72504a
vendor/github.com/gobwas/ws/wsutil.ReadData(0x7f8d484ab220, 0xc46798c5b8, 0xc48b1db001, 0xc48b1db0b0, 0x410608, 0x84baa0, 0x8ac780, 0x782800, 0x7f8d484ab220)
	/data/jenkins/workspace/src/xxxxxx/vendor/github.com/gobwas/ws/wsutil/helper.go:88 +0x47 fp=0xc48b1db068 sp=0xc48b1db010 pc=0x724b07
vendor/github.com/gobwas/ws/wsutil.ReadClientData(0x7f8d484ab220, 0xc46798c5b8, 0xc46798c5b8, 0x7f8d484ab220, 0xc46798c5b8, 0x0, 0xc45ffdfc20, 0x24)
	/data/jenkins/workspace/src/xxxxxx/vendor/github.com/gobwas/ws/wsutil/helper.go:97 +0x3a fp=0xc48b1db0c0 sp=0xc48b1db068 pc=0x724baa
devserv.acceptWebsocket(0xaf9e40, 0xc4312cd420, 0xc42fcf8200)
	/data/jenkins/workspace/src/xxxxxx/devserv/devserv.go:343 +0x1a9c fp=0xc48b1dbc80 sp=0xc48b1db0c0 pc=0x7828fc
devserv.(*myHttpServerMux).ServeHTTP(0xb34038, 0xaf9e40, 0xc4312cd420, 0xc42fcf8200)
	/data/jenkins/workspace/src/xxxxxx/devserv/devserv.go:85 +0x151 fp=0xc48b1dbd18 sp=0xc48b1dbc80 pc=0x780811
net/http.serverHandler.ServeHTTP(0xc420174340, 0xaf9e40, 0xc4312cd420, 0xc42fcf8200)
	/usr/lib/golang/src/net/http/server.go:2619 +0xb4 fp=0xc48b1dbd48 sp=0xc48b1dbd18 pc=0x6d5284
net/http.(*conn).serve(0xc44a55dcc0, 0xafa680, 0xc46c8cd880)
	/usr/lib/golang/src/net/http/server.go:1801 +0x71d fp=0xc48b1dbfc8 sp=0xc48b1dbd48 pc=0x6d154d
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:2337 +0x1 fp=0xc48b1dbfd0 sp=0xc48b1dbfc8 pc=0x45e001
created by net/http.(*Server).Serve
	/usr/lib/golang/src/net/http/server.go:2720 +0x288
```
version:v1.0.0
go version:1.10.2
Is the connection broken?

**Comment by Slach** [comment]
look like you don't have enought memory for allocate in NewCipherReader

**Comment by changlin19** [comment]
But there's 50% more memory in the server

**Comment by gobwas** [comment]
Hello @changlin19. What OS is on your server?

**Comment by gobwas** [comment]
Does it relates to https://github.com/gobwas/ws/pull/60 somehow?
