### ISSUE TITLE
unsafe pointer conversion at util.go:233

### ISSUE THREAD

**Issue by eliasnaur** [gobwas/ws#93]
Running a program with the Go 1.14 pointer checks enabled through `-race` leads to the detection of an invalid pointer conversion:

```
$ go test -race gioui.org/cmd/gogio
--- FAIL: TestJS (5.43s)
panic: runtime error: unsafe pointer conversion [recovered]
    panic: runtime error: unsafe pointer conversiongoroutine 35 [running]:
testing.tRunner.func1(0xc00017e200)
    /Users/elias/go-tip/src/testing/testing.go:888 +0xaeb
panic(0x1a11860, 0xc0001bc040)
    /Users/elias/go-tip/src/runtime/panic.go:915 +0x370
github.com/gobwas/ws.btsEqualFold(0xc0001fc034, 0x9, 0xfcc, 0x2058b08, 0x9, 0x9, 0xc0001fc034)
    /Users/elias/go/pkg/mod/github.com/gobwas/ws@v1.0.2/util.go:233 +0x184
github.com/gobwas/ws.Dialer.Upgrade(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /Users/elias/go/pkg/mod/github.com/gobwas/ws@v1.0.2/dialer.go:374 +0xe72
github.com/gobwas/ws.Dialer.Dial(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
    /Users/elias/go/pkg/mod/github.com/gobwas/ws@v1.0.2/dialer.go:190 +0x444
github.com/gobwas/ws.Dial(...)
    /Users/elias/go/pkg/mod/github.com/gobwas/ws@v1.0.2/dialer.go:47
github.com/chromedp/chromedp.DialContext(0x1b85740, 0xc0000903c0, 0xc00003eaf0, 0x4a, 0xc000105750, 0x1, 0x1, 0x18fb783, 0xc0000102d0, 0x0)
    /Users/elias/go/pkg/mod/github.com/chromedp/chromedp@v0.5.1/conn.go:59 +0xff
github.com/chromedp/chromedp.NewBrowser(0x1b85780, 0xc000033ce0, 0xc00003eaf0, 0x4a, 0xc000010040, 0x1, 0x1, 0x0, 0x0, 0x0)
    /Users/elias/go/pkg/mod/github.com/chromedp/chromedp@v0.5.1/browser.go:99 +0x3bb
github.com/chromedp/chromedp.(*ExecAllocator).Allocate(0xc0001dc000, 0x1b85780, 0xc000033ce0, 0xc000010040, 0x1, 0x1, 0x0, 0x0, 0x0)
    /Users/elias/go/pkg/mod/github.com/chromedp/chromedp@v0.5.1/allocate.go:220 +0xfec
github.com/chromedp/chromedp.Run(0x1b85780, 0xc000033ce0, 0x0, 0x0, 0x0, 0xc00000e300, 0x2)
    /Users/elias/go/pkg/mod/github.com/chromedp/chromedp@v0.5.1/chromedp.go:210 +0x311
gioui.org/cmd/gogio_test.(*JSTestDriver).Start(0xc00000e060, 0xc00017e200, 0x1a643b5, 0xf, 0x320, 0x258, 0x2d00008, 0x0, 0xc00000e060)
    /Users/elias/proj/gio/cmd/gogio/js_test.go:81 +0x928
gioui.org/cmd/gogio_test.runEndToEndTest(0xc00017e200, 0x1b836c0, 0xc00000e060)
    /Users/elias/proj/gio/cmd/gogio/e2e_test.go:42 +0xa8
gioui.org/cmd/gogio_test.TestJS(0xc00017e200)
    /Users/elias/proj/gio/cmd/gogio/js_test.go:155 +0xad
testing.tRunner(0xc00017e200, 0x1a87048)
    /Users/elias/go-tip/src/testing/testing.go:925 +0x1a9
created by testing.(*T).Run
    /Users/elias/go-tip/src/testing/testing.go:976 +0x652
FAIL    gioui.org/cmd/gogio    5.458s
FAIL
```

**Comment by cristaloleg** [comment]
Link to the code https://github.com/gobwas/ws/blob/master/util.go#L233

**Comment by mvdan** [comment]
I'm encountering the same... @gobwas any chance this could get looked at soon? 1.14 will ship in two months, and there is lots of software out there that uses the data race detector, which enables this check and will fail with your current version.

**Comment by gobwas** [comment]
Hi @mvdan, chances are high now – Im planning to work on ws during next weeks.

**Comment by gobwas** [comment]
Hey guys, closing this since it seems to be fixed long ago. 🍻
