### ISSUE TITLE
"fatal error: checkptr: unsafe pointer conversion" with Go 1.14 und race detector

### ISSUE THREAD

**Issue by vdobler** [gobwas/ws#99]
Running ws compiled with Go 1.14 under the race detector (e.g. during `go test -race`) aborts with the following error:

```
fatal error: checkptr: unsafe pointer conversion

goroutine 122 [running]:
runtime.throw(0x1f0854e, 0x23)
	/usr/local/go/src/runtime/panic.go:1112 +0x72 fp=0xc00062cdd0 sp=0xc00062cda0 pc=0x1073eb2
runtime.checkptrAlignment(0xc000448035, 0x1d8b100, 0x1)
	/usr/local/go/src/runtime/checkptr.go:13 +0xd0 fp=0xc00062ce00 sp=0xc00062cdd0 pc=0x1045ba0
github.com/gobwas/ws.btsEqualFold(0xc000448034, 0x9, 0xfcc, 0x2818c38, 0x9, 0x9, 0xc000448034)
	/Users/m0252720/go/pkg/mod/github.com/gobwas/ws@v1.0.2/util.go:233 +0x184 fp=0xc00062ce68 sp=0xc00062ce00 pc=0x1c42ee4
github.com/gobwas/ws.Dialer.Upgrade(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/m0252720/go/pkg/mod/github.com/gobwas/ws@v1.0.2/dialer.go:374 +0xe72 fp=0xc00062d0f8 sp=0xc00062ce68 pc=0x1c3dfd2
github.com/gobwas/ws.Dialer.Dial(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/m0252720/go/pkg/mod/github.com/gobwas/ws@v1.0.2/dialer.go:190 +0x444 fp=0xc00062d480 sp=0xc00062d0f8 pc=0x1c3c2e4
github.com/gobwas/ws.Dial(...)
	/Users/m0252720/go/pkg/mod/github.com/gobwas/ws@v1.0.2/dialer.go:47
```

Go 1.14 added a new checkptr compile time option which tests for proper handling of unsafe.Pointer values, see https://golang.org/doc/go1.14#compiler for details.
It seems as if ws doesn't follow the unsafe.Pointer safety guidelines strictly enough.

The problem can be reproduced on master:

    $ GO111MODULE=off go test -race github.com/gobwas/ws

**Comment by mvdan** [comment]
It looks like upstream is reviewing a patch, so all seems to be going as planned. Thanks @cristaloleg for your help!

**Comment by gobwas** [comment]
Must be fixed now by @cristaloleg! Thanks a lot, man!
